name: Notify Telegram on Push
on:
  push:
    branches:
      - main
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Message
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COMMIT_URL: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          AUTHOR="${{ github.event.head_commit.author.name }}"
          TEXT="🧠 New commit to ToyMania:\n\n*${COMMIT_MSG}*\nby ${AUTHOR}\n\n🔗 [View Commit](${COMMIT_URL})"
          curl -s -X POST https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d parse_mode=Markdown \
          --data-urlencode text="$TEXT"
